// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/config.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/config.go -destination=internal/mocks/config_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDotfileConfigLoader is a mock of DotfileConfigLoader interface.
type MockDotfileConfigLoader struct {
	ctrl     *gomock.Controller
	recorder *MockDotfileConfigLoaderMockRecorder
	isgomock struct{}
}

// MockDotfileConfigLoaderMockRecorder is the mock recorder for MockDotfileConfigLoader.
type MockDotfileConfigLoaderMockRecorder struct {
	mock *MockDotfileConfigLoader
}

// NewMockDotfileConfigLoader creates a new mock instance.
func NewMockDotfileConfigLoader(ctrl *gomock.Controller) *MockDotfileConfigLoader {
	mock := &MockDotfileConfigLoader{ctrl: ctrl}
	mock.recorder = &MockDotfileConfigLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDotfileConfigLoader) EXPECT() *MockDotfileConfigLoaderMockRecorder {
	return m.recorder
}

// GetDotfileTargets mocks base method.
func (m *MockDotfileConfigLoader) GetDotfileTargets() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDotfileTargets")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetDotfileTargets indicates an expected call of GetDotfileTargets.
func (mr *MockDotfileConfigLoaderMockRecorder) GetDotfileTargets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDotfileTargets", reflect.TypeOf((*MockDotfileConfigLoader)(nil).GetDotfileTargets))
}

// GetExpandDirectories mocks base method.
func (m *MockDotfileConfigLoader) GetExpandDirectories() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpandDirectories")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetExpandDirectories indicates an expected call of GetExpandDirectories.
func (mr *MockDotfileConfigLoaderMockRecorder) GetExpandDirectories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpandDirectories", reflect.TypeOf((*MockDotfileConfigLoader)(nil).GetExpandDirectories))
}

// GetIgnorePatterns mocks base method.
func (m *MockDotfileConfigLoader) GetIgnorePatterns() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIgnorePatterns")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetIgnorePatterns indicates an expected call of GetIgnorePatterns.
func (mr *MockDotfileConfigLoaderMockRecorder) GetIgnorePatterns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIgnorePatterns", reflect.TypeOf((*MockDotfileConfigLoader)(nil).GetIgnorePatterns))
}
