// Code generated by MockGen. DO NOT EDIT.
// Source: internal/state/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/state/types.go -destination=internal/mocks/core_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
