# golangci-lint configuration for Plonk
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 10m
  tests: true

linters:
  # Use 'none' as default and explicitly enable what we want
  default: none
  enable:
    # Original linters
    - govet         # Standard Go static analysis
    - ineffassign   # Detect ineffectual assignments
    - misspell      # Fix spelling mistakes
    - unused        # Find unused code

    # Error handling
    - errcheck      # Check for unchecked errors
    - errorlint     # Proper error wrapping and checking

    # Static analysis
    - staticcheck   # Advanced static analysis (includes gosimple)

    # Security
    - gosec         # Security-focused checks

    # Code quality
    - gocyclo       # Cyclomatic complexity
    - nolintlint    # Ensure nolint directives are justified

  # Exclusion configuration
  exclusions:
    # Enable presets for common exclusions
    presets:
      - std-error-handling
      - common-false-positives

    # Custom exclusion rules
    rules:
      # Exclude some linters from test files
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - errorlint
          - staticcheck
      # Exclude test utilities
      - path: internal/testutil/
        linters:
          - errcheck
          - gosec

  settings:
    misspell:
      locale: US

    errcheck:
      # Functions where ignoring the error is acceptable
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net.Conn).Close
        - (*bufio.Writer).Flush
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Println
        - fmt.Printf
        - os.Remove
        - os.RemoveAll
        - os.Setenv
        - os.Unsetenv
        - os.Chdir
        - (*cobra.Command).RegisterFlagCompletionFunc

    gocyclo:
      # Standard complexity threshold; specific high-complexity formatters use //nolint:gocyclo
      min-complexity: 30

    gosec:
      excludes:
        # G104: Audit errors not checked - handled by errcheck exclude-functions
        - G104
        # G301: Directory permissions - we use standard 0755 for config dirs
        - G301
        # G302: File permissions - we use standard 0644 for readable config files
        - G302
        # G306: WriteFile permissions - we use 0644 for config files intentionally
        - G306
        # G404: Weak random number generator - used for non-security test data
        - G404

    nolintlint:
      # Require an explanation for nolint directives
      require-explanation: true
      require-specific: true

output:
  formats:
    text:
      print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
