# golangci-lint v2 configuration for Plonk
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet         # Standard Go static analysis
    - errcheck      # Check for unchecked errors
    - ineffassign   # Detect ineffectual assignments
    - misspell      # Fix spelling mistakes
    - unused        # Find unused code
    - godot         # Check comments end with period
    - gocritic      # Style, performance, and bug checks

formatters:
  goimports:
    local-prefixes: plonk
  
  gofmt:
    simplify: true

linters.settings:
  govet:
    shadow: true
  
  errcheck:
    check-type-assertions: true
  
  misspell:
    locale: US
  
  godot:
    scope: all
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult  # Sometimes unnamed returns are clearer

issues:
  max-issues-per-linter: 0
  max-same-issues: 0