# golangci-lint configuration for Plonk
# Compatible with both v1 and v2 config formats
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
    - govet         # Standard Go static analysis
    - ineffassign   # Detect ineffectual assignments
    - misspell      # Fix spelling mistakes
    - unused        # Find unused code

linters-settings:
  govet:
    shadow: true

  misspell:
    locale: US


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
