# GoReleaser configuration for plonk
# Documentation: https://goreleaser.com
version: 2

before:
  hooks:
    # Ensure module dependencies are tidy
    - go mod tidy
    # Run tests before release
    - go test ./...

builds:
  - id: plonk
    main: ./cmd/plonk
    binary: plonk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Skip certain combinations
    ignore:
      - goos: windows
        goarch: arm64
    # Custom ldflags for version info
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: plonk-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - tar.gz
      - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^style:'
      - '^refactor:'
      - '^perf:'
      - '^ci:'
  groups:
    - title: '🚀 Features'
      regexp: '^feat'
    - title: '🐛 Bug Fixes'
      regexp: '^fix'
    - title: '🔒 Security'
      regexp: '^sec'
    - title: '⚠️ Breaking Changes'
      regexp: '^.*!:'
    - title: 'Other Changes'

release:
  github:
    owner: richhaase
    name: plonk
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Plonk v{{.Version}}

    A unified package and dotfile manager for developers.
  footer: |
    ---

    **Full Changelog**: https://github.com/richhaase/plonk/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Installation

    ### Homebrew
    ```bash
    brew tap richhaase/tap
    brew install plonk

    # Or install directly:
    brew install richhaase/tap/plonk
    ```

brews:
  - name: plonk
    repository:
      owner: richhaase
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/richhaase/plonk"
    description: "The unified package and dotfile manager for developers who tinker"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    caveats: |
      Plonk requires Homebrew to be installed as a prerequisite.
      Get started with:
        plonk --help
        plonk clone <your-github-username>/dotfiles
      Documentation: https://github.com/richhaase/plonk#readme

# Announce releases on social media (optional)
announce:
  skip: true

# Sign releases with GPG (disabled - requires GPG setup)
# signs:
#   - artifacts: checksum
