// Code generated by MockGen. DO NOT EDIT.
// Source: internal/state/package_provider.go
//
// Generated by this command:
//
//	mockgen -source=internal/state/package_provider.go -destination=internal/state/mock_package_interfaces.go -package=state
//

// Package state is a generated GoMock package.
package state
