// Code generated by MockGen. DO NOT EDIT.
// Source: internal/state/reconciler.go
//
// Generated by this command:
//
//	mockgen -source=internal/state/reconciler.go -destination=internal/state/mock_provider.go -package=state
//

// Package state is a generated GoMock package.
package state
