// Code generated by MockGen. DO NOT EDIT.
// Source: internal/resources/packages/common.go
//
// Generated by this command:
//
//	mockgen -source=internal/resources/packages/common.go -destination=internal/resources/packages/mock_manager.go -package=packages
//

// Package packages is a generated GoMock package.
package packages
