name: 'Setup Go Environment'
description: 'Setup Go, install dependencies, and optionally install development tools'
inputs:
  go-version:
    description: 'Go version to install (default: from go.mod)'
    required: false
    default: ''
  install-homebrew:
    description: 'Install Homebrew on Linux (default: false)'
    required: false
    default: 'false'
  install-just:
    description: 'Install Just task runner (default: false)'
    required: false
    default: 'false'
  cache-key-suffix:
    description: 'Additional suffix for cache key (default: none)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version != '' && inputs.go-version || 'stable' }}
        go-version-file: ${{ inputs.go-version == '' && 'go.mod' || '' }}
        cache: true
        cache-dependency-path: |
          go.sum
          tools/tools.go

    - name: Download dependencies
      run: go mod download
      shell: bash

    - name: Install Homebrew (Linux)
      if: ${{ inputs.install-homebrew == 'true' && runner.os == 'Linux' }}
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      shell: bash

    - name: Install Just
      if: ${{ inputs.install-just == 'true' }}
      uses: extractions/setup-just@v3

    - name: Verify Go installation
      run: |
        echo "✅ Go version: $(go version)"
        echo "✅ Go environment ready"
      shell: bash