// Code generated by MockGen. DO NOT EDIT.
// Source: internal/managers/common.go
//
// Generated by this command:
//
//	mockgen -source=internal/managers/common.go -destination=internal/managers/mock_manager.go -package=managers
//

// Package managers is a generated GoMock package.
package managers
