name: Security Check
on: [pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Run vulnerability scan
      run: go run golang.org/x/vuln/cmd/govulncheck ./...

    - name: Run security scan
      run: go run github.com/securego/gosec/v2/cmd/gosec ./... || true
